### ISSUE TITLE
standard UAC bypass doesn't work on windows 10

### ISSUE THREAD

**Issue by ankushgoel27** [qdba/MyBashBunny#1]
Hi,

The UAC bypass- standard works for windows 7 but doesn't work for windows 10. can you please help. The other one(specific to win 10) works.

**Comment by qdba** [comment]
It dependes on the security hole. The UAC Bypass in Windows 7 was fixed in 10 the the Standard does not wor.

**Comment by ankushgoel27** [comment]
thanks
